'''
Contains the definitions of several important paths for data input and output. Also contains a couple of convenience
functions
'''

import os
from GJEphys.KKHAXLParsing import parseMetaDataFile, getExpIDsByCategory

'''
A folder to store all data. All input data, intermediate processed data and output data will be collected in the folder
"<homeFolder>/DataAndResults/ephys".

(SMR files containing raw electrophysiological traces need to be manually placed in "spike2Path" below)
'''
homeFolder = "/home/aj/"

'''
Path to the excel file containing all metadata
'''
excel = os.path.join(homeFolder, 'DataAndResults/Ginjang-Metadata/neuron_database.xlsx')

'''
Name of the sheet of "excel" containing metadata of all experiments
'''
excelSheet = 'Kai-san final report150803'

'''
Folder where the NIX files generated by importing raw SMR files will be stored. These will be expanded with more 
information after imported files are processed.
'''
NIXPath = os.path.join(homeFolder, 'DataAndResults/ephys/NIXFiles/')

'''
Folder where SMR files containing raw traces are to be found 
'''
spike2Path = os.path.join(homeFolder, 'DataAndResults/ephys/Ginjang-Ephys/')

'''
String to which ".pdf" will be appended to form the path where statistics about continuous stimulii trials 
will be written 
'''
contStimsResultsFile = os.path.join(homeFolder, 'DataAndResults', 'ephys', 'Results', 'contStimStats')

'''
Path where an excel file containing a table of trial counts will be written for continuous stimuli responses.
'''
contStimDetailedStatsFile = os.path.join(homeFolder, "DataAndResults", "ephys", "Results", "contStimDetailedStats.xlsx")

'''
String to which ".pdf" will  be appended to form the path where statistics about pulse stimulii trials will be written.
'''
pulseStimsSummaryStatsFile = os.path.join(homeFolder, 'DataAndResults', 'ephys', 'Results', 'pulseStimStats')

'''
Path where an excel file containing a table of trial counts of pulse stimulii will be written.
'''
pulseStimsDetailedStatsFile = os.path.join(homeFolder, 'DataAndResults', 'ephys', 'Results', 'pulseStimDetailedStats.xlsx')

'''
Path where the success/failure of importing raw traces from SMR files is recorded when running 
GJEphys.scripts.usedInPubs.rawDataImporter
'''
importResultsFile = os.path.join(NIXPath, "ImportResults.xlsx")

'''
Path where the success/failure of processing NIX files is recorded when running 
GJEphys.scripts.usedInPubs.rawDataProcessor
'''

processedResultsFile = os.path.join(NIXPath, "processingResults.xlsx")

'''
A pandas.DataFrame containing metadata about experiments.
'''
mdDF = parseMetaDataFile(excel, excelSheet, spike2Path)

'''
List of all neuron categories.
'''
categories = [
                'DL-Int-1',
                'DL-Int-2',
                'JO neuron',
                'MB neurons',
                'BilateralN',
                'DescendingN',
                'AscendingN',
                'Bilateral Descending N',
                'JO terminal local neuron'
            ]


def getAllExpNames():
    '''
    returns a list of all experiment IDs present in the metadata excel file and with a correponding SMR file.
    :return: list
    '''
    expNames = map(str, mdDF.index)
    return expNames


def allExpIDsByCat():
    '''
    Returns a dictionary with all neuron categories as keys and lists of corresponding Experiment Ids as values
    :return: dict
    '''

    return getExpIDsByCategory(excel, excelSheet, categories, spike2Path)